version: '3'
services:
  soundlevelmeter:
    build: 
      ./sensor-container
    volumes: 
      - ./resources:/resources
      - ./sync:/sync
    environment:
      - SOUND_DATA_PATH=/resources/soundlevel.txt
    restart: unless-stopped
    networks:
      - city-noisepollution-network


  soundlevelmonitor:
    build: ./monitor-container
    environment: 
      - AVG_POLLUTION_PATH=/resources/noisepollution.txt
      - SOUND_DATA_PATH=/resources/soundlevel.txt
    volumes:
    - ./resources:/resources
    - ./sync:/sync
    restart: unless-stopped 
    networks:
      - city-noisepollution-network

networks:
   city-noisepollution-network:
      driver: bridge